### PR TITLE
typo: activate changes to enable in systemctl

### PR DESCRIPTION
**Pull request by pachadotdev**

### CODE REVIEW

**Comment by trestletech** [comment]
Hi. Thanks for contributing.

I'm unfortunately not familiar enough with systemctl to know off the top of my head which is right. Do you have any context here on what distro/version you're using and what the results of either were?

**Comment by pachadotdev** [comment]
That was used on Ubuntu Server 16.04 LTS
systemctl is standard across Debian based distros, I had to build another
API and I found the typo in the docs

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk

**Comment by pachadotdev** [comment]
@trestletech Hi! I checked on Debian 9 and the correct verb is `enable` and then `start`

**Comment by pachadotdev** [comment]
Hi @trestletech. Just a reminder about this fixed typo to improve the documentation. Best!

**Comment by schloerke** [comment]
Fixed in #25

**Comment by pachadotdev** [comment]
@schloerke hi, tradestatistics.io is pure sql + plumber + shiny :) you may want to give a look to it

**Pull request closed without merging**
